version: '2'
services:

  # Base Image to build project
  compiler-dps:
    image: golang:1.9
    working_dir: /app/src/github.com/mageddo/dns-proxy-server
    volumes:
      - $PWD:/app/src/github.com/mageddo/dns-proxy-server
      - $PWD/builder:/bin/builder
      - /var/run/docker.sock:/var/run/docker.sock
    command: tail -f /dev/null
    environment:
      - TERM=xterm
      - GOPATH=/app
      - MG_WORK_DIR=/app/src/github.com/mageddo/dns-proxy-server
    hostname: dns-proxy-server.dev
    network_mode: bridge

  # Run from docker image
  prod-dps:
    image: defreitas/dns-proxy-server:2.5.4
    hostname: dns.mageddo
    volumes:
      - /opt/dns-proxy-server/conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    ports:
      - 5380:5380
    network_mode: bridge

  # Build the project and generate binary at build folder
  prod-build-binary-dps:
    extends: compiler-dps
    container_name: docker-dns-server-compiler
    command: bash -c "builder build"

  # Build project and generate docker image you will need to run prod-build-image-dps first
  prod-build-image-dps:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-dns-server-docker-compiler
    image: defreitas/dns-proxy-server:2.5.4

  # build the project and make the github release
  prod-ci-deploy:
    container_name: prod-ci-deploy
    extends: compiler-dps
    command: bash -c "builder deploy-ci"
    environment:
      - CURRENT_BRANCH=$TRAVIS_BRANCH # current branch name
      - REPO_TOKEN=$REPO_TOKEN # github token to deploy the binary
    volumes:
      - $HOME/.gitconfig:/root/.gitconfig
